[package]
name = "actions"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
image = { version = "0.23.0", default-features = false, features = ["jpeg", "png", "gif"] }
base64 = "0.12"